version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t gateway .
      - docker tag gateway:latest 911031080079.dkr.ecr.us-east-1.amazonaws.com/gateway:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 911031080079.dkr.ecr.us-east-1.amazonaws.com/gateway:latest
      - printf '[{"name":"gateway","imageUri":"%s"}]' 911031080079.dkr.ecr.us-east-1.amazonaws.com/gateway:latest > image.json
artifacts:
  files:
    - image.json
